import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2-nervous-system/chapter1-foundations',
        'module-1-ros2-nervous-system/chapter2-nodes-topics-services',
        'module-1-ros2-nervous-system/chapter3-rclpy',
        'module-1-ros2-nervous-system/chapter4-urdf',
        'module-1-ros2-nervous-system/chapter5-middleware-in-action',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/intro',
        {
          type: 'category',
          label: 'Chapter 1: Digital Twin Fundamentals',
          items: [
            'module-2-digital-twin/chapter1-intro/digital-twins-fundamentals',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Gazebo Simulation',
          items: [
            'module-2-digital-twin/chapter2-gazebo/gazebo-setup',
            'module-2-digital-twin/chapter2-gazebo/physics-engines',
            'module-2-digital-twin/chapter2-gazebo/environment-creation',
            'module-2-digital-twin/chapter2-gazebo/ros-bridge',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Unity Visualization',
          items: [
            'module-2-digital-twin/chapter3-unity/unity-setup',
            'module-2-digital-twin/chapter3-unity/rendering-pipelines',
            'module-2-digital-twin/chapter3-unity/robot-importing',
            'module-2-digital-twin/chapter3-unity/hri-simulation',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: Sensor Simulation',
          items: [
            'module-2-digital-twin/chapter4-sensors/lidar-simulation',
            'module-2-digital-twin/chapter4-sensors/depth-cameras',
            'module-2-digital-twin/chapter4-sensors/rgb-cameras',
            'module-2-digital-twin/chapter4-sensors/imu-simulation',
            'module-2-digital-twin/chapter4-sensors/ros-data-streams',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 5: Validation & Reality Gap',
          items: [
            'module-2-digital-twin/chapter5-validation/sim-to-real-gap',
            'module-2-digital-twin/chapter5-validation/noise-models',
            'module-2-digital-twin/chapter5-validation/behavioral-testing',
            'module-2-digital-twin/chapter5-validation/benchmarking',
            'module-2-digital-twin/chapter5-validation/case-study',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Isaac Integration for Humanoid Navigation',
      items: [
        'module-3-isaac-integration/intro',
        {
          type: 'category',
          label: 'Chapter 1: Isaac Sim Scene Setup',
          items: [
            'module-3-isaac-integration/isaac-sim-scene-setup',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: VSLAM-Nav2 Integration',
          items: [
            'module-3-isaac-integration/vslam-nav2-integration',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Navigation Architecture',
          items: [
            'module-3-isaac-integration/nav2-architecture',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: Mapping and Localization',
          items: [
            'module-3-isaac-integration/mapping-localization',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 5: Global and Local Planners',
          items: [
            'module-3-isaac-integration/global-local-planners',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 6: Biped Controllers',
          items: [
            'module-3-isaac-integration/biped-controllers',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 7: Collision Avoidance and Safety',
          items: [
            'module-3-isaac-integration/collision-avoidance-safety',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 8: Navigation Performance and Safety',
          items: [
            'module-3-isaac-integration/navigation-performance-safety',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        'module-4-vla/intro',
        // 'module-4-vla/architecture',
        // 'module-4-vla/vision-encoder',
        // 'module-4-vla/language-core',
        // 'module-4-vla/action-policy',
        // 'module-4-vla/safety-supervisor',
        // 'module-4-vla/execution-layer',
        // 'module-4-vla/api-reference',
        // 'module-4-vla/glossary',
        // 'module-4-vla/examples',
      ],
    },
  ],
};

export default sidebars;